travis:
  secure:
    BINSTAR_TOKEN: EGpYXmupT8aAsiiGwCbbKg8fRGHFzZuJcqE04zAYSpk7vFqa69wXeukjuzw7+KvcmoIUkseCZV9ZYyYypavfJurcA28vb/nKYSe/WQLjHeTWB9G47LB5ynh8A0Ppn/CnU8uIH35rLzHs1g/1j6PBITCwDG9QtZkk8JUmlvIjRhsMY2sBC7IIE3JhFM7A9/0xS2LYJCkcvvFSwB23sfY11atcML90hKf3Xzht1jzk39t6zqTQ81yRU4YrDAuuEEbLl6oEIgKWwBXgYACS+f0ga0Qtp09HO4noMR8VUTrliSN33suHipZasw6wbIJ9/iWwWVAtXXXLLmIT1FWYAwElKlubbxTjDWwpV75AzZRO7uSCFhj50nGj7rpZbJQE9MobtU8vv7MeGbwrKXAJFHIaWYtWN8KvyzS/bNRpqkZKb38n1AEB00ZjPStlln4XD8xRs44A5pV68yxU76w85MxOZnrP8j76tjCuebWHuId9QrMuYVbulMxzcP+wDeYOWec+MyXI1TmGz2FPKIPk4dvvYDuRnjHQYDi37oamvakKqj+zSrFHDZk6Zxu2uxAIs6BT3dGRvtt4GvRPsdHyGWOt/AgWztDvdf3ixa9VKeWBvhKrkCMzECb9idS94d5a3S+uSkiBGAEonF3JkVFxl6nLWESC0cYpFucdT49qSg8pS8k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
